name: Publish Demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install pnpm and gh-pages
        run: |
          npm install -g gh-pages@3.0.0
          npm install -g pnpm
      - name: Install Dependencies
        run: |
          pnpm install
      - name: Build Website
        run: |
          npx pilet build 'pilets/*' --type standalone
          echo "todo-mvc.samples.piral.cloud" > dist/standalone1/CNAME
          cp dist/standalone/index.html dist/standalone/404.html
      - name: Deploy Website
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          gh-pages -d "dist/standalone" -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
